language: swift
xcode_scheme: Danger
osx_image: xcode11.1

before_install:
- bundle install
- gem update fastlane cocoapods --no-document
- pod repo update

script:
- fastlane ci
- bundle exec danger

after_success:
  # generate docs
- jazzy --xcodebuild-arguments -scheme,DangerTest --module DangerTest --source-directory DangerTest --readme README.md