language: swift
xcode_workspace: Danger.xcworkspace
xcode_scheme: Danger
osx_image: xcode11.1

before_install:
- bundle install
- gem update fastlane cocoapods --no-document

script:
- fastlane ci

after_success:
  # generate docs
- jazzy --xcodebuild-arguments -scheme,DangerTest --module DangerTest --source-directory DangerTest --readme README.md

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  on:
    branch: master